(const_declaration) @keyword
(let_declaration) @keyword
(arrow_function) @keyword
(block_comment) @comment
(inline_comment) @comment
(start_tag) @tag
(end_tag) @tag
(for_block) @tag
(variable) @variable
